all: README.md

README.md: guessinggame.sh
	echo "# Unix Workbench course week 4 peer-graded assignment #" > README.md
	echo "## Project: **JH-UW4** ##" >> README.md
	echo -n "This file was generated by *'make'* on: " >> README.md
	date >> README.md
	echo -n "The number of lines of code in *guessinggame.sh* is: " >> README.md
	wc -l < guessinggame.sh >> README.md

clean:
	rm README.md



